\begintext
Metakernel for use with KRC.
Object: 
52 EUROPA
Kernels up-to-date as of 2026.07.06
Generated by kernel_mgmt.py
\begindata
PATH_VALUES=(
    '/home/nsmith/KRC/pyorb/kernels',
)
PATH_SYMBOLS=(
    'k',
)
KERNELS_TO_LOAD=(
'$k/lsk/naif0012.tls',
'$k/pck/pck00011.tpc',
'$k/spk/de442.bsp',
'$k/spk/20003779.bsp',
)
