	SUBROUTINE ALBVAR (Q1, ALBV)
C_Titl ALBVAR Compute frost albedo as linear function of insolation
C INPUTS:
C Q1 = AVERAGE (OVER A DAY) SOLAR FLUX ( DIRECT AND DIFFUSE) 
C   INCIDENT ON A FLAT SURFACE
C OUTPUTS
C ALBV = EFFECTIVE HEMISPHERIC ALBEDO OF FROST DEPOSIT
C	?? SHOULD PHASE FUNCTION BE HERE??
	INCLUDE 'krccom.inc'
C GETS INDEPENDANT PARAMETERS FROM KRCCOM
	EQUIVALENCE (AF1,FD(29)), (AF2,FD(30))
C
	ALBV = AF1 + AF2*Q1
	RETURN
	END
