\begintext
Metakernel for use with KRC.
Kernels up-to-date as of 2026.07.21
Generated by kernel_mgmt.py
\begindata
PATH_VALUES=(
    './kernels',
)
PATH_SYMBOLS=(
    'k',
)
KERNELS_TO_LOAD=(
'$k/lsk/naif0012.tls',
'$k/pck/pck00011.tpc',
'$k/spk/de442.bsp',
)
