\begintext
Metakernel for use with KRC.
Object: 
KIEFFER
Kernels up-to-date as of 2026.07.06
Generated by kernel_mgmt.py
\begindata
PATH_VALUES=(
    './test/kernels/input/test3',
)
PATH_SYMBOLS=(
    'k',
)
KERNELS_TO_LOAD=(
'$k/lsk/naif0012.tls',
'$k/pck/pck00011.tpc',
'$k/spk/de442.bsp',
'$k/spk/20003779.bsp',
)
