C_Titl FILCOM.INC  Common for file names and other strings
        CHARACTER*80 FINPUT,FOUT,FDISK,FVALB,FVTAU
        CHARACTER*20 TITONE     ! title for each one-point line
        CHARACTER*12 VERSIN ! version number
        COMMON /FILCOM/ FINPUT,FOUT,FDISK,FVALB,FVTAU,TITONE,VERSIN
C_Hist   85oct14  Hugh_Kieffer  97feb12 increase string length
C 2002mar01 HK increase string length from 60
C 2006sep09 HK Add FVALB,FVTAU
C 2009may10 HK Add TITONE
C 2013jan30 HK Add VERSIN
C_End___________________________________________________________________________
