	SUBROUTINE PORBQQ	! test computation of matrixes
C HHK 85JAN15   85sep13=revise call argument order
C 2009dec24 HK modify PI to PICON

	INCLUDE 'porbcm.inc'
	REAL*4 EQ(9),FE(9),FQQ(9)

	CALL ROTDIA (1., EQ)
	CALL ROTAX  (1,OBL, EQ)
	CALL MPRINT ('EQ',EQ,IOP)
	CALL ROTDIA (1., FE)
	CALL ROTAX  (3,ZFEB+PICON/2., FE)
	CALL ROTAX  (1,ZFEC, FE)
	CALL ROTAX  (3,XFEXB+PICON, FE)
		CALL MPRINT ('FE',FE,IOP)
	CALL MPROD3 (FE,EQ, FQQ)
		CALL MPRINT ('FQ=FE*EQ',FQQ,IOP)
	CALL MPROD3 (EQ,FE, FQQ)
		CALL MPRINT ('EQ*FE',FQQ,IOP)
	RETURN
	END
